#%RAML 1.0
title: Epidemik
version: v0.1
mediaType: application/json
baseUri: https://epidemik.us/api.php
types:
  NewUser:
    properties: 
      username: string
      password: string
      latitude: number
      longitude: number
      deviceID: string
      date_of_birth: date-only
      gender: 
        type: string
        enum: ["male", "female", "other"]
    example:
      username: "test"
      password: "%123f67abc"
      latitude: 61.4
      longitude: 72.8
      deviceID: "12345a423"
      date_of_birth: "1973-02-21"
      gender: "male"

  User:
    properties: 
      latitude: number
      longitude: number
      date_of_birth: date-only
      gender:
        type: string
        enum: ["male", "female", "other"]
      diseases: Disease[]
    example:
      latitude: 61.4
      longitude: 72.8
      date_of_birth: "1973-02-21"
      gender: "male"
      diseases: [
        {
          disease_name: "Common Cold"
          date_sick: "2018-03-01"
          date_healthy: "2018-03-12"
          symptoms: [symID: 1,symID: 3,symID: 5]
        }
      ]

  Disease:
    properties:
      disease_name: string
      date_sick: date-only
      date_healthy: date-only | nil
      symptoms: Symptom[]
    examples:
      not_sick:
        disease_name: "Common Cold"
        date_sick: "2018-03-01"
        date_healthy: "2018-03-12"
        symptoms: [symID: 1,symID: 3,symID: 5]   
      still_sick:
        disease_name: "Common Cold"
        date_sick: "2018-03-01"
        date_healthy: nil
        symptoms: [symID: 1,symID: 3,symID: 5]   

  Region:
    properties: 
      lat_min: number
      long_min: number
      lat_max: number
      long_max: number
    example:
      lat_min: 0
      long_min: 0
      lat_max: 50
      long_max: 50

  Symptom:
    properties: 
      symID: number
    example:
      symID: 1

  Trend:
    properties: 
      latitude: number
      longitude: number
      trend_weight: number
      disease_name: string
    example:
      latitude: 50.1
      longitude: 50.1
      trend_weight: 30.45
      disease_name: "Common Cold"
  HistoricalTrend:
    properties: 
      percent: number
      date: date-only
    example:
      percent: 0.50
      date: "1999-06-12"

/users:
  post:
    description: Adds a new user.
    queryParameters: 
      version:
        displayName: Version
        type: string
        description: The current version of the app the user is using.
        example: 1.0
        required: true
    body:
      application/json:
        type: NewUser

    responses:
        201:
          body:
            application/json:
              type: string
            example: "#12akjcns&^sanus&^"
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        403:
          body:
            properties:
              error: string
            examples:
             userExists: 
              error: "Username already used"
             bad_password: 
              error: "Invalid Password"
  get:
    description: Return every disease every user has ever had.
    queryParameters: 
      version:
        displayName: Version
        type: string
        description: The current version of the app the user is using.
        example: 1.0
        required: true
      auth_token:
        displayName: Authorization Token
        type: string
        description: The authorization token the user was given when they logged in.
        example: "#12akjcns&^sanus&^"
        required: true

    responses:
      426:
        body:
          application/json:
            type: string
          example: "Version out of date"
      401:
        body:
          application/json:
            type: string
          example: "Bad Authorization Token"
      200:
        body:
          application/json:
            type: User[]

  /{userID}:
    put:
      description: Changes this users password and gives back the new salt.
      queryParameters: 
        version:
          displayName: Version
          type: string
          description: The current version of the app the user is using.
          example: 1.0
          required: true
        auth_token:
          displayName: Authorization Token
          type: string
          description: The authorization token the user was given when they logged in.
          example: "#12akjcns&^sanus&^"
          required: true
        new_password:
          displayName: New Password
          type: string
          description: The new password for the user account.
          example: "password"
          required: true

      responses:
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        401:
          body:
            application/json:
              type: string
            example: "Bad Authorization Token"
        202:
          body:
            application/json:
              type: string
    patch:
      description: Changes this users address.
      queryParameters: 
        latitude:
          displayName: Latitude
          type: string
          description: The new latitude of the user
          example: 1.0
          required: true
        longitude:
          displayName: Longitude
          type: string
          description: The new longitude of the user
          example: 1.0
          required: true
        auth_token:
          displayName: Authorization Token
          type: string
          description: The authorization token the user was given when they logged in.
          example: "#12akjcns&^sanus&^"
          required: true
        new_password:
          displayName: New Password
          type: string
          description: The new password for the user account.
          example: "password"
          required: true

      responses:
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        401:
          body:
            application/json:
              type: string
            example: "Bad Authorization Token"
        204:


    delete:
      description: Removes this user and all associated information.
      queryParameters: 
        version:
          displayName: Version
          type: string
          description: The current version of the app the user is using.
          example: 1.0
          required: true
        auth_token:
          displayName: Authorization Token
          type: string
          description: The authorization token the user was given when they logged in.
          example: "#12akjcns&^sanus&^"
          required: true
      responses:
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        401:
          body:
            application/json:
              type: string
            example: "Bad Authorization Token"
        204:

    get:
      description: Returns information about this specific user.
      queryParameters: 
        version:
          displayName: Version
          type: string
          description: The current version of the app the user is using.
          example: 1.0
          required: true
        auth_token:
          displayName: Authorization Token
          type: string
          description: The authorization token the user was given when they logged in.
          example: "#12akjcns&^sanus&^"
          required: true

      responses:
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        401:
          body:
            application/json:
              type: string
            example: "Bad Authorization Token"
        200:
          body:
            application/json:
              type: User

    /diseases:
      patch:
        description: Marks this user as healthy.
        queryParameters: 
          version:
            displayName: Version
            type: string
            description: The current version of the app the user is using.
            example: 1.0
            required: true
          auth_token:
            displayName: Authorization Token
            type: string
            description: The authorization token the user was given when they logged in.
            example: "#12akjcns&^sanus&^"
            required: true
          date_healthy:
            displayName: Date Healthy
            type: date-only
            description: The date the user because healthy on. Not required. If not included, marks as healthy today.
            example: "2015-04-05"
            required: false
        responses:          
          426:
            body:
              application/json:
                type: string
              example: "Version out of date"
          401:
            body:
              application/json:
                type: string
              example: "Bad Authorization Token"
          204:

      post:
        description: Put a new sickness in this users records.
        queryParameters: 
          version:
            displayName: Version
            type: string
            description: The current version of the app the user is using.
            example: 1.0
            required: true
          auth_token:
            displayName: Authorization Token
            type: string
            description: The authorization token the user was given when they logged in.
            example: "#12akjcns&^sanus&^"
            required: true
        body:
          application/json:
            type: Disease
        responses:          
          426:
            body:
              application/json:
                type: string
              example: "Version out of date"
          401:
            body:
              application/json:
                type: string
              example: "Bad Authorization Token"
          200:
            body:
              application/json:
                type: string
              description: Returns the name of the disease that the backend thinks you have.
            example: "Common Cold"

      get:
        description: Return information about this users sickness. 
        queryParameters: 
          version:
            displayName: Version
            type: string
            description: The current version of the app the user is using.
            example: 1.0
            required: true
          auth_token:
            displayName: Authorization Token
            type: string
            description: The authorization token the user was given when they logged in.
            example: "#12akjcns&^sanus&^"
            required: true
        responses:          
          426:
            body:
              application/json:
                type: string
              example: "Version out of date"
          401:
            body:
              application/json:
                type: string
              example: "Bad Authorization Token"
          200:
            body:
              application/json:
                type: Disease[]

      /{diseaseID}:
        delete:
          description: Removes this specific disease.
          queryParameters: 
            version:
              displayName: Version
              type: string
              description: The current version of the app the user is using.
              example: 1.0
              required: true
            auth_token:
              displayName: Authorization Token
              type: string
              description: The authorization token the user was given when they logged in.
              example: "#12akjcns&^sanus&^"
              required: true
          responses:          
            426:
              body:
                application/json:
                  type: string
                example: "Version out of date"
            401:
              body:
                application/json:
                  type: string
                example: "Bad Authorization Token"
            204:

        get:
          description: Returns information about this disease.
          queryParameters: 
            version:
              displayName: Version
              type: string
              description: The current version of the app the user is using.
              example: 1.0
              required: true
            auth_token:
              displayName: Authorization Token
              type: string
              description: The authorization token the user was given when they logged in.
              example: "#12akjcns&^sanus&^"
              required: true
          responses:          
            426:
              body:
                application/json:
                  type: string
                example: "Version out of date"
            401:
              body:
                application/json:
                  type: string
                example: "Bad Authorization Token"
            200:
              body:
                application/json:
                  type: Disease

        /symptoms:
          get:
            description: Returns all information about this disease's symptoms. 
            queryParameters: 
              version:
                displayName: Version
                type: string
                description: The current version of the app the user is using.
                example: 1.0
                required: true
              auth_token:
                displayName: Authorization Token
                type: string
                description: The authorization token the user was given when they logged in.
                example: "#12akjcns&^sanus&^"
                required: true
            responses:          
              426:
                body:
                  application/json:
                    type: string
                  example: "Version out of date"
              401:
                body:
                  application/json:
                    type: string
                  example: "Bad Authorization Token"
              200:
                body:
                  application/json:
                    type: Symptom[]

          /{symptomID}:
            delete:
              description: Removes this symptom from this diseases list of symptoms. 
              queryParameters: 
                version:
                  displayName: Version
                  type: string
                  description: The current version of the app the user is using.
                  example: 1.0
                  required: true
                auth_token:
                  displayName: Authorization Token
                  type: string
                  description: The authorization token the user was given when they logged in.
                  example: "#12akjcns&^sanus&^"
                  required: true
              responses:          
                426:
                  body:
                    application/json:
                      type: string
                    example: "Version out of date"
                401:
                  body:
                    application/json:
                      type: string
                    example: "Bad Authorization Token"
                204:
    
    /symptoms:
      post:
        description: Puts a new symptom in this users list of current symptoms.
        queryParameters: 
          version:
            displayName: Version
            type: string
            description: The current version of the app the user is using.
            example: 1.0
            required: true
          auth_token:
            displayName: Authorization Token
            type: string
            description: The authorization token the user was given when they logged in.
            example: "#12akjcns&^sanus&^"
            required: true
        body:
          application/json:
            type: Symptom
            description: The symptom you wish to report. 
        responses:          
          426:
            body:
              application/json:
                type: string
              example: "Version out of date"
          401:
            body:
              application/json:
                type: string
              example: "Bad Authorization Token"
          200:
            body:
              application/json:
                type: string
              description: Returns the symptom ID of the new symptom.

      get:
        description: Returns all the information about this users current symptoms.
        queryParameters: 
          version:
            displayName: Version
            type: string
            description: The current version of the app the user is using.
            example: 1.0
            required: true
          auth_token:
            displayName: Authorization Token
            type: string
            description: The authorization token the user was given when they logged in.
            example: "#12akjcns&^sanus&^"
            required: true
        responses:          
          426:
            body:
              application/json:
                type: string
              example: "Version out of date"
          401:
            body:
              application/json:
                type: string
              example: "Bad Authorization Token"
          200:
            body:
              application/json:
                type: Symptom[]
    /sickness:
      get:
        description: Returns whether or not this user is sick (true if sick)
        queryParameters: 
          version:
            displayName: Version
            type: string
            description: The current version of the app the user is using.
            example: 1.0
            required: true
          auth_token:
            displayName: Authorization Token
            type: string
            description: The authorization token the user was given when they logged in.
            example: "#12akjcns&^sanus&^"
            required: true
        responses:          
          426:
            body:
              application/json:
                type: string
              example: "Version out of date"
          401:
            body:
              application/json:
                type: string
              example: "Bad Authorization Token"
          200:
            body:
              application/json:
                type: boolean


/diseases:
  get:
    description: Returns information about every disease in the requested region.
    queryParameters: 
      version: 
        displayName: Version
        type: string
        description: The current version of the app the user is using.
        example: 1.0
        required: true
      auth_token:
        displayName: Authorization Token
        type: string
        description: The authorization token the user was given when they logged in.
        example: "#12akjcns&^sanus&^"
        required: true
      region:
        displayName: Query Region
        type: Region
        description: The region the user wishes to get data in.
        required: true
    responses:          
      426:
        body:
          application/json:
            type: string
          example: "Version out of date"
      401:
        body:
          application/json:
            type: string
          example: "Bad Authorization Token"
      200:
        body:
          application/json:
            type: Disease[]

  /{disease_name}:
    get:
      description: Returns information about every disease matching this disease name in the requested region.
      queryParameters: 
        version:
          displayName: Version
          type: string
          description: The current version of the app the user is using.
          example: 1.0
          required: true
        auth_token:
          displayName: Authorization Token
          type: string
          description: The authorization token the user was given when they logged in.
          example: "#12akjcns&^sanus&^"
          required: true
        region:
          displayName: Query Region
          type: Region
          description: The region the user wishes to get data in.
          required: true
      responses:          
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        401:
          body:
            application/json:
              type: string
            example: "Bad Authorization Token"
        200:
          body:
            application/json:
              type: Disease[]

    /symptoms:
      get:
        description: Returns information about every symptom matching this disease name in the requested region.
        queryParameters: 
          version:
            displayName: Version
            type: string
            description: The current version of the app the user is using.
            example: 1.0
            required: true
          auth_token:
            displayName: Authorization Token
            type: string
            description: The authorization token the user was given when they logged in.
            example: "#12akjcns&^sanus&^"
            required: true
        responses:          
          426:
            body:
              application/json:
                type: string
              example: "Version out of date"
          401:
            body:
              application/json:
                type: string
              example: "Bad Authorization Token"
          200:
            body:
              application/json:
                type: Symptom[][]

/trends:
  get:
    description: Returns information about all the disease trends in the requested region
    queryParameters: 
      version:
        displayName: Version
        type: string
        description: The current version of the app the user is using.
        example: 1.0
        required: true
      auth_token:
        displayName: Authorization Token
        type: string
        description: The authorization token the user was given when they logged in.
        example: "#12akjcns&^sanus&^"
        required: true
      latitude:
        displayName: Latitude
        type: number
        description: The latitude the user wishes to get data in.
        required: true
      longitude:
        displayName: Longitude
        type: number
        description: The longitude the user wishes to get data in.
        required: true
    responses: 
      426:
        body:
          application/json:
            type: string
          example: "Version out of date"
      401:
        body:
          application/json:
            type: string
          example: "Bad Authorization Token"
      200:
        body:
          application/json:
            type: Trend[]
  /{userID}:
    get:
      description: Returns information about all the disease trends in this users region
      queryParameters: 
        version:
          displayName: Version
          type: string
          description: The current version of the app the user is using.
          example: 1.0
          required: true
        auth_token:
          displayName: Authorization Token
          type: string
          description: The authorization token the user was given when they logged in.
          example: "#12akjcns&^sanus&^"
          required: true
      responses: 
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        401:
          body:
            application/json:
              type: string
            example: "Bad Authorization Token"
        200:
          body:
            application/json:
              type: Trend[]
  /historical:
    get:
      description: Returns information about all the historical infections in the users region
      queryParameters: 
        version:
          displayName: Version
          type: string
          description: The current version of the app the user is using.
          example: 1.0
          required: true
        auth_token:
          displayName: Authorization Token
          type: string
          description: The authorization token the user was given when they logged in.
          example: "#12akjcns&^sanus&^"
          required: true
        latitude:
          displayName: Latitude
          type: number
          description: The latitude the user wishes to get data in.
          required: true
        longitude:
          displayName: Longitude
          type: number
          description: The longitude the user wishes to get data in.
          required: true
      responses: 
        426:
          body:
            application/json:
              type: string
            example: "Version out of date"
        401:
          body:
            application/json:
              type: string
            example: "Bad Authorization Token"
        200:
          body:
            application/json:
              type: HistoricalTrend[]
/login:
  post:
    description: Returns the auth token if sucessful
    queryParameters: 
      version:
        displayName: Version
        type: string
        description: The current version of the app the user is using.
        example: 1.0
        required: true
      username:
        displayName: Username
        type: number
        description: The username of the user.
        required: true
      password:
        displayName: Password
        type: number
        description: The password of the user.
        required: true
    responses: 
      426:
        body:
          application/json:
            type: string
          example: "Version out of date"
      401:
        body:
          application/json:
            type: string
          example: "Incorrect login"
      204:
        body:
          application/json:
            type: string

      
